name: PuhuTV Güncelleme Botu

on:
  schedule:
    # Her gün UTC saatiyle 00:00'da çalışır (Türkiye saatiyle 03:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # Elle tetiklemek için buton ekler

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Repoya dosya yazma izni verir

    steps:
      - name: Repoyu Çek (Checkout)
        uses: actions/checkout@v4

      - name: Python Kurulumu (3.9)
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Python Scriptini Çalıştır
        run: python puhutv.py

      - name: Değişiklikleri Kontrol Et ve Commit At
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # HTML dosyasını git'e ekle
          git add puhutv.html
          
          # Eğer değişiklik varsa commit at ve pushla, yoksa hata verme
          git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik Güncelleme: puhutv.html [$(date)]" && git push)
          
