name: ShowTV VOD Scraper

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repo'yu Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python Kütüphanelerini Kur
        run: |
          pip install requests beautifulsoup4 lxml unidecode tqdm urllib3

      - name: Scraper'ı Çalıştır
        run: |
          python show.py

      - name: Git yapılandırması
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name  "GitHub Actions"

      - name: Son değişiklikleri çek (rebase)
        run: |
          git pull --rebase

      - name: HTML Çıktısını Commit Et
        run: |
          git add show.html
          git commit -m "ShowTV güncellendi [$(date +"%Y-%m-%d %H:%M:%S")]"
          git push
